load artifacts/testdata/tbl/tpch/sf-0.001/customer.tbl customer
load artifacts/testdata/tbl/tpch/sf-0.001/lineitem.tbl lineitem
load artifacts/testdata/tbl/tpch/sf-0.001/nation.tbl nation
load artifacts/testdata/tbl/tpch/sf-0.001/orders.tbl orders
load artifacts/testdata/tbl/tpch/sf-0.001/part.tbl part
load artifacts/testdata/tbl/tpch/sf-0.001/partsupp.tbl partsupp
load artifacts/testdata/tbl/tpch/sf-0.001/region.tbl region
load artifacts/testdata/tbl/tpch/sf-0.001/supplier.tbl supplier
    